import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from "@/components/common/Navbar";
import React from "react";
import Footer from "@/components/common/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Gestionnaire de contact',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={'flex flex-col min-h-screen'}>
          <Navbar />
          <main className={"flex-grow"}>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
